### PR TITLE
add sass and less mixins to readme

### PR DESCRIPTION
**Pull request by amaldare93**
I made these mixins to make it easier and more intuitive to use this polyfill. I figured I'd share them with anyone else who would like to use them.

The default values come straight from the spec.

Let me know if you would like these in a different spot or phrased a different way, or if you don't want them in the readme at all, thats fine too.

Either way, I love the polyfill, I'm going to convince my job to start using this on Monday!

### CODE REVIEW

**Comment by amaldare93** [comment]
Yea thats a better idea, I'm on it.

**Comment by amaldare93** [comment]
@bfred-it fixed

**Comment by fregante** [comment]
Can you squash that into a single commit? I'll probably merge tomorrow

**Comment by amaldare93** [comment]
done :+1:

**Comment by fregante** [comment]
Manually merged and added some fixes. I'm sure I did it wrong but your commit is up there :)

https://github.com/bfred-it/object-fit-images/commits/gh-pages

**Pull request closed without merging**
