### PR TITLE
Fix/support safari

### PR DESCRIPTION
**Pull request by amaldare93**
Now fixes images in Safari (and keeps them draggable).
Also added browser-sync to devDependencies.

### CODE REVIEW

**Comment by fregante** [comment]
Thanks! A few notes:

Supporting `object-fit` in Safari means [breaking `srcset` support](https://github.com/bfred-it/object-fit-images/blob/gh-pages/detailed-support-tables.md#object-fit-images--srcset) in some older versions (I'm unsure of which ones but the reason is that they don't support `currentSrc`), iOS 8.4 is one of them.

In Safari, OFI needs to only act when `object-position` is present and `srcset` isn't, because generally it's more important to support `object-fit` + `srcset` than `object-fit` + `object-position`. The solution is more complicated than it appears.

---

The image actually becomes a transparent gif, so even if it's draggable, you're only dragging the gif. The only way around it is finding a way to hide the ``'s image without hiding the `` itself (because that'd hide the `background-image` too)

---

Work on the the latest version instead of creating duplicate/[merge commits](https://github.com/bfred-it/object-fit-images/commit/d89e1d405216dffed3778e916a617f1cb3213eec). I know GH doesn't offer an easy way to [sync forks](https://help.github.com/articles/syncing-a-fork/)

I can only import the browser-sync commit from here

**Comment by amaldare93** [comment]
Ahh I didn't know that... it _did_ seem suspiciously easy to fix so that makes sense.

Sorry about all the extra commits and stuff tho, this is my first time contributing to open source.

**Comment by fregante** [comment]
No worries, you're doing well! I've been here for a while and I still mess it up! I mean I can't even cherry-pick your browser-sync commit for example, can you do another PR? Perhaps avoid the slash in the commit branch because that might have been what's preventing me from pulling it in, I'm not sure

Thanks again for contributing :)

**Comment by amaldare93** [comment]
yea sure, the slash is just a habit I picked up from work.

**Pull request closed without merging**
