### PR TITLE
fix: file path of image trans to background-image

### PR DESCRIPTION
**Pull request by yulinyeh**
when file path of image includes '(' or ')', using in background-image: url() will be fail.

### CODE REVIEW

**Comment by fregante** [comment]
Thanks! Sorry for the late reply. Happy new year!

**Comment by yulinyeh** [comment]
No worries, thank you and Happy new year :)

**Comment by fregante** [comment]
Going through some GH issues yesterday I found that I had already applied a solution to this: https://github.com/bfred-it/object-fit-images/issues/14

Did you have issues before? Did this change fix it for you?

**Comment by yulinyeh** [comment]
I found that when the filename contained '(' and ')', it couldn't be displayed correctly, so i changed it to '%28' and '%29'

**Pull request merged**
