### PR TITLE
Added link to CDN

### PR DESCRIPTION
**Pull request by paulradzkov**

### CODE REVIEW

**Comment by fregante** [comment]
That's good to have but I'd rather not have to update the README file every time I push a new version. Can you replace that with an explanation of how to use unpkg? Perhaps replace the version with something like PLACE.OFI'S.VERSION.HERE and a note about that.

**Comment by fregante** [comment]
`@latest` is a bad idea because if the API changes, the sites will break. It's best not to have it copy-pastable at all.

I changed the wording to make it safer. Thanks for the PR!

**Comment by paulradzkov** [comment]
Maybe you'd like to use  
`https://unpkg.com/object-fit-images@2.x.x/dist/ofi.browser.js` 
or   
`https://unpkg.com/object-fit-images@2.5.x/dist/ofi.browser.js`

It is safer and provides direct working link.

**Comment by fregante** [comment]
That solves the issue, true, but it requires two requests (the first one is a redirect) of a file that honestly shouldn't be loaded via CDN at all, given that it's a mere KB (it should just be bundled)

**Pull request merged**
